on: [push]

jobs:
  custom_action:
    runs-on: [self-hosted, linux, X64, ets-cloud]
    steps:
      - name: custom action
        uses: manulife-ets-sandbox/test_action@v1.1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
