on: 
  push:
    branches: [main]

jobs:
  custom_action:
    runs-on: [self-hosted, linux, X64, ets-cloud]
    steps:
      - name: custom action
        id: custom_action
        uses: manulife-ets-sandbox/test_action@v1.2
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.custom_action.outputs.random-number }}
        shell: bash
