on: 
  push:
    branches: [main, develop]

jobs:
  validate_cookbook:
    runs-on: [self-hosted, linux, X64, ets-cloud]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract Chef Server
        shell: bash
        id: extract_chefserver
        run: |
          if [ "${{ steps.extract_branch.outputs.branch }}" == "main" ]; then
            echo "##[set-output name=chefserver;]$(echo prod)"
          else
            echo "##[set-output name=chefserver;]$(echo sandbox)"
          fi
      - name: show chef server
        shell: bash
        run: |
          echo "chef server is ${{ steps.extract_chefserver.outputs.chefserver }}"
          echo "current branch is ${{ steps.extract_branch.outputs.branch }}"
      - name: validate cookbook
        id: validate_cookbook
        uses: manulife-ets-sandbox/validate_cookbook@latest
        with:
          chef_key: ${{ secrets.CHEF_SVC_KEY }}
          chef_server: ${{ steps.extract_chefserver.outputs.chefserver }}

