on: 
  push:
    branches: [main, develop]

jobs:
  upload_cookbook:
    runs-on: [self-hosted, linux, X64, ets-cloud]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Extract Chef Server
        shell: bash
        id: extract_chefserver
        run: |
          if [ "${GITHUB_REF#refs/heads/}" == "main" ]; then
            echo "##[set-output name=chefserver;]$(echo prod)"
          elif [ "${GITHUB_REF#refs/heads/}" == "develop" ]; then
            echo "##[set-output name=chefserver;]$(echo sandbox)"
          else
            echo "Branch name invalid. This action can only be triggered by \"main\" or \"develop\" branch"
            exit 1
          fi
      - name: show chef server
        shell: bash
        run: |
          echo "target chef server is ${{ steps.extract_chefserver.outputs.chefserver }}"
      - name: Import Secrets
        id: retrieve_secret
        uses: hashicorp/vault-action@v2.1.2
        with:
          url: https://vault.prod.cac.platform.manulife.io:443
          method: approle
          roleId: bf50f9e9-2cca-beac-6cfa-8db32dae9614
          secretId: ${{ secrets.VAULT_CHEF_SECRET_ID }}
          namespace: ETS-CLOUDPLATFORM-IAC-3365
          tlsSkipVerify: true
          secrets: 
            secret/data/chef_delivery chef_delivery_key | CHEF_DELIVERY_KEY ;
            secret/data/chef_delivery INTERNAL_REPO_READ_TOKEN | INTERNAL_REPO_READ_TOKEN 
      - name: Check out validate cookbook action
        uses: actions/checkout@v2 
        with:
          repository: manulife-ets/validate_cookbook
          ref: testing
          token: ${{ steps.retrieve_secret.outputs.INTERNAL_REPO_READ_TOKEN }}
          path: .github/actions/validate_cookbook
      - name: validate cookbook
        uses: ./.github/actions/validate_cookbook
        with:
          chef_key: ${{ steps.retrieve_secret.outputs.CHEF_DELIVERY_KEY }}
          chef_server: ${{ steps.extract_chefserver.outputs.chefserver }}
      - name: Check out upload cookbook action
        uses: actions/checkout@v2
        with:
          repository: manulife-ets/upload_cookbook
          ref: latest
          token: ${{ steps.retrieve_secret.outputs.INTERNAL_REPO_READ_TOKEN }}
          path: .github/actions/upload_cookbook
      - name: upload cookbook
        uses: ./.github/actions/upload_cookbook
        with:
          chef_key: ${{ steps.retrieve_secret.outputs.CHEF_DELIVERY_KEY }}
          chef_server: ${{ steps.extract_chefserver.outputs.chefserver }}
          github_token: ${{ secrets.GITHUB_TOKEN }}